version: "3.7"
services:

    # Imagem
    laravel_microservices_rabbitmq_micro_email:
        build:
            args:
                user: ezequieldhonatan
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis_micro_email
            - queue
        networks:
            - microemail

    # Nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8005:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microemail

    # Queue
    queue:
        build:
            args:
                user: ezequieldhonatan
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        networks:
            - microemail

    # Redis
    redis_micro_email:
        image: redis:latest
        networks:
            - microemail

networks:
    microemail:
        driver: bridge
